server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/user/**
        - id: accounts
          uri: http://localhost:8084
          predicates:
            - Path=/accounts/**
        - id: transactions
          uri: http://localhost:8082
          predicates:
            - Path=/transactions/**
        - id: advisor
          uri: http://localhost:8088
          predicates:
            - Path=/advisor/**
      default-filters:
        - PreserveHostHeader

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE
