server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: accounts
          uri: http://localhost:8084
          predicates:
            - Path=/accounts/**
        - id: transactions
          uri: http://localhost:8082
          predicates:
            - Path=/transactions/**
        - id: advisor
          uri: http://localhost:8088
          predicates:
            - Path=/advisor/**
      default-filters:
        - RemoveRequestHeader=Cookie

management:
  endpoints:
    web:
      exposure:
        include: health,info
