server:
  port: 8084

spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/zariya_accounts_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 12345678
  flyway:
    url: jdbc:mysql://localhost:3306/mysql
    user: root
    password: 12345678
    enabled: true
    locations: classpath:db/migration
    schemas: zariya_accounts_db
    default-schema: zariya_accounts_db
    create-schemas: true
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate.format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

cache:
  type: redis

management:
  endpoints.web.exposure.include: health,info
