server:
  port: 8085

spring:
  application:
    name: audit
  datasource:
    url: jdbc:mysql://localhost:3306/zariya_audit_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 12345678
  flyway:
    url: jdbc:mysql://localhost:3306/mysql
    user: root
    password: 12345678
    enabled: true
    locations: classpath:db/migration
    schemas: zariya_audit_db
    default-schema: zariya_audit_db
    create-schemas: true
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate.format_sql: true

management:
  endpoints.web.exposure.include: health,info
