server:
  port: 8082

spring:
  application:
    name: transactions
  data:
    mongodb:
      uri: mongodb://localhost:27017/transactions_db

management:
  endpoints.web.exposure.include: health,info
logging.level.org.springframework: info
