server:
  port: 8081

spring:
  application:
    name: auth-users
  datasource:
    url: jdbc:mysql://localhost:3306/zariya_auth_users_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/mysql
    user: root
    password: 12345678
    enabled: true
    locations: classpath:db/migration
    schemas: zariya_auth_users_db
    default-schema: zariya_auth_users_db
    create-schemas: true

management:
  endpoints:
    web.exposure.include: health,info
logging:
  level:
    org.springframework: info

security:
  jwt:
    secret: "zariyapay-secret-key-that-is-32-bytes!"
    expiration: 3600000

